version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - '2181:2181'

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - TOPIC_AUTO_CREATE=false
            - DELETE_TOPIC_ENABLE=true
        depends_on:
            - zookeeper

    mysql_database:
    # Replace 'your_username' and 'your_password' with your actual MySQL credentials
        image: mysql
        container_name: mysql_database
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=frud_database
          - MYSQL_USER=Galal_Ewida
          - MYSQL_PASSWORD=1234
        volumes:
          - ./mysql_data:/var/lib/mysql

    phpmyadmin:
      depends_on:
        - mysql_database 
      image: phpmyadmin/phpmyadmin
      ports:
      - '8080:80'
      environment:
        PMA_HOST: mysql_database
        MYSQL_ROOT_PASSWORD: 1234
        PMA_USER: Galal_Ewida
        PMA_PASSWORD: 1234
       
     
  

   